env:
  GITHUB_USER=mlenkeit
  PORT=3555 
  PROJECTS_JSON=./test/fixture/projects.json
  
language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm run test
  - node scripts/install-svc.js -u max -t 123 -p 3000 -P hello.json --forever-path my-forever --node-path my-node