env:
  GITHUB_USER=mlenkeit
  PORT=3555 
  PROJECTS=./test/fixture/projects.js
  
language: node_js
node_js:
  - "8"
  - "10"
script:
  - npm run lint
  - npm run coverage:unit
  - npm run coverage-check
  - npm run test:system
cache:
  directories:
    - node_modules