env:
  GITHUB_USER=mlenkeit
  PORT=3555 
  PROJECTS=./test/fixture/projects.js
  PROJECTS_CONFIG=/usr/src/projects/mlenkeit/pi-dab/test/fixture/projects-docker.json
services:
  - docker  
git:
  depth: false # otherwise, e2e tests might not find certain commits to checkout
language: node_js
node_js:
  - "12.4.0"
script:
  - docker --version
  - docker-compose --version
  - npm run lint
  - npm run fixture
  - npm run coverage:unit
  - npm run coverage-check
  - npx kill-port --port $PORT
  - curl "https://$LOCALTUNNEL_HOST" # wake up  dyno
  - npm run test:system
  - npx kill-port --port $PORT
  - docker-compose build
  - npm run test:docker
cache:
  directories:
    - node_modules