env:
  GITHUB_USER=mlenkeit
  PORT=3555 
  PROJECTS=./test/fixture/projects.js
services:
  - docker  
git:
  depth: false # otherwise, e2e tests might not find certain commits to checkout
language: node_js
node_js:
  - "12.4.0"
script:
  - docker --version
  - docker-compose --version
  - npm run lint
  - npm run fixture
  - npm run coverage:unit
  - npm run coverage-check
  - npm run test:system
  - docker-compose build
  - npm run test:docker
cache:
  directories:
    - node_modules