FROM mlenkeit/node-compose:latest

# App
ENV PORT 3000

WORKDIR /usr/src/app

COPY package-lock.json /usr/src/app/package-lock.json
COPY package.json /usr/src/app/package.json
RUN npm install --production

COPY lib /usr/src/app/lib
COPY launcher /usr/src/app/launcher

EXPOSE 3000
CMD [ "node", "launcher/launcher.js" ]